run:
  build-tags:
    - nolic

  tests: true

  skip-dirs:
    - api
    - test

linters:
  presets:
    - bugs
    - unused
    - format
    - style
  disable:
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - lll
    - unparam
    - dupl
    - wsl
  exclude-use-default:
    - should not use dot imports

issues:
  exclude:
    - should not use dot imports
#  exclude-rules:
#    - linters:
#        - golint
#        - stylecheck
#      text: "should not use dot imports"
